# Generated by Django 5.1.1 on 2025-04-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='phone',
        ),
    ]
